[programs.localnet]
token_faucet = "BkGzzYK5LkUAPcMM643AcSjRSP9PgWzVd6NryAQ3QSW"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/thinkwsl/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
