[programs.mainnet]
token_faucet = "Ce3x2Wup3hNWDcNnLuXRjB9msb8aRn6xX8U5aq1fTYrN"

[programs.devnet]
token_faucet = "Ce3x2Wup3hNWDcNnLuXRjB9msb8aRn6xX8U5aq1fTYrN"

[programs.testnet]
token_faucet = "Ce3x2Wup3hNWDcNnLuXRjB9msb8aRn6xX8U5aq1fTYrN"

[programs.localnet]
token_faucet = "Ce3x2Wup3hNWDcNnLuXRjB9msb8aRn6xX8U5aq1fTYrN"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"